customer = {
    "customerid": "la-la",
    "gender": "male",
    "seniorcitizen": 0,
    "partner": "no",
    "dependents": "no",
    "tenure": 12,
    "phoneservice": "yes",
    "multiplelines": "yes",
    "internetservice": "fiber_optic",
    "onlinesecurity": "no",
    "onlinebackup": "no",
    "deviceprotection": "no",
    "techsupport": "no",
    "streamingtv": "no",
    "streamingmovies": "yes",
    "contract": "month-to-month",
    "paperlessbilling": "no",
    "paymentmethod": "electronic_check",
    "monthlycharges": 63.05,
    "totalcharges": 1299.3,
}

